### PR TITLE
null safety

### PR DESCRIPTION
**Pull request by lazicah**
Migrated to null safety

### CODE REVIEW

**Comment by fuadrivai** [comment]
is it support for web or desktop?

**Comment by kechankrisna** [comment]
> is it support for web or desktop?

you can try this package 
https://pub.dev/packages/pos_printer_manager

**Comment by fuadrivai** [comment]
> > is it support for web or desktop?
> 
> you can try this package
> https://pub.dev/packages/pos_printer_manager

hi @kechankrisna , thanks for the reply, i will try it

**Comment by selvam920** [comment]
pls merge this null safety

**Pull request merged**
